# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('todo', models.CharField(max_length=100)),
                ('flag', models.CharField(default='1', max_length=2)),
                ('priority', models.CharField(default='0', max_length=2)),
                ('pubtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
