# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20171211_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='pubtime',
            new_name='creattime',
        ),
    ]
